# Generated by Django 5.2.1 on 2025-06-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_signup_groups_signup_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
