# Generated by Django 5.2.1 on 2025-06-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_alter_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('pactype', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('Sname', models.CharField(max_length=100)),
                ('Snumber', models.CharField(max_length=10)),
                ('Saddress', models.CharField(max_length=255)),
                ('Saddress1', models.CharField(blank=True, max_length=255, null=True)),
                ('Rname', models.CharField(max_length=100)),
                ('Rnumber', models.CharField(max_length=10)),
                ('Raddress', models.CharField(max_length=255)),
                ('Raddress1', models.CharField(blank=True, max_length=255, null=True)),
                ('payments', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('COD', 'COD')], max_length=50)),
                ('service', models.CharField(choices=[('Door to Door', 'Door to Door'), ('Office Collect', 'Office Collect')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.FloatField()),
                ('pieces', models.PositiveIntegerField()),
                ('Bookby', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Booking_list',
            },
        ),
    ]
