# Generated by Django 5.2.1 on 2025-06-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_booking_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_list',
            name='cn_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
