# Generated by Django 5.2.1 on 2025-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_alter_booking_list_cn_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_list',
            name='cn_no',
            field=models.CharField(max_length=20),
        ),
    ]
