# Generated by Django 5.2.1 on 2025-06-14 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0009_alter_booking_list_cn_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_no', models.CharField(max_length=100)),
                ('payments', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('COD', 'COD')], max_length=50)),
                ('date', models.DateField()),
                ('sname', models.CharField(max_length=100)),
                ('snumber', models.CharField(max_length=15)),
                ('pactype', models.CharField(max_length=100)),
                ('pieces', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rname', models.CharField(max_length=100)),
                ('raddress', models.TextField()),
                ('rnumber', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'booking_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField()),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PdfParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CN_No', models.CharField(max_length=50, unique=True, verbose_name='Consignment Number')),
                ('date', models.DateField(verbose_name='Date of Booking')),
                ('country', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('payments', models.CharField(max_length=100)),
                ('Sname', models.CharField(max_length=100, verbose_name='Sender Name')),
                ('Snumber', models.CharField(max_length=20, verbose_name='Sender Phone Number')),
                ('Saddress', models.TextField(verbose_name='Sender Address')),
                ('Rname', models.CharField(max_length=100, verbose_name='Receiver Name')),
                ('Rnumber', models.CharField(max_length=20, verbose_name='Receiver Phone Number')),
                ('Raddress', models.TextField(verbose_name='Receiver Address')),
                ('pieces', models.PositiveIntegerField(verbose_name='Number of Pieces')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Charges (Rs.)')),
                ('service', models.CharField(max_length=100, verbose_name='Service Type')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Weight (KG)')),
                ('Bookby', models.CharField(max_length=100, verbose_name='Booked By')),
            ],
            options={
                'db_table': 'booking_list',
            },
        ),
    ]
