# Generated by Django 5.2.1 on 2025-06-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0010_bookinglist_complaint_pdfparcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
